### ISSUE TITLE
Default-optional use case only functions for 'castable' types

### ISSUE THREAD

**Issue by jackirvine97** [brocksam/pyproprop#3]
https://github.com/brocksam/pyproprop/blob/a21d41293bb83d46e1d474e0c3ba4a062fd10f3e/pyproprop/processed_property.py#L126
  
`some_property = processed_property("some_property", type=SomeType, optional=True, default=some_type_instance)`

In the above use case, when `some_property` is set to `None`, pyproprop attempts to cast `some_type_instance` to `SomeType` and return the result (see referenced line in `processed_property.py)` . If `SomeType` is not 'castable' this raises an error.

Might it be more intuitive to simply return the user-supplied default value in this use case?

**Comment by brocksam** [comment]
I think this makes sense and the way it is currently operating is actually a bug. @jackirvine97 can you please write a test that will pass for the intended functionality then I can implement the logic for the next release?

**Comment by jackirvine97** [comment]
I am happy to amend the test suite and implement the fix myself in a PR
