### ISSUE TITLE
Error in post method

### ISSUE THREAD

**Issue by jackirvine97** [brocksam/pyproprop#48]
When calling a processed property with a post method, for example: 

```
squares = processed_property(
        "squares",
        type=int,
        iterable_allowed=True,
        method=square()
)
```
 The following is raised: `NameError: name 'optional' is not defined`.

This is comping from line `processed_property` line 537:
https://github.com/brocksam/pyproprop/blob/693950be09186100bc029535ddaef0e9f61eb4f9/pyproprop/processed_property.py#L524-L539

Optional is not is in the scope of `apply_method`.

**Comment by brocksam** [comment]
Is this in 0.4.0? Can you please post the full minimal reproducer so I can add to the test suite and go about fixing?

**Comment by jackirvine97** [comment]
This is 0.4.0 yes.
```
  File "lapysim/test.py", line 7, in <module>
    event.new_event_phase("some_event")
  File "/event.py", line 546, in new_event_phase
    new_event_phase = EventPhase(
  File "/event.py", line 98, in __init__
    self.athletes = athletes
  File "/Users/JackIrvine/opt/anaconda3/envs/jackirvine/lib/python3.8/site-packages/pyproprop/processed_property.py", line 207, in prop
    value = method(value, *args, **kwargs)
  File "/Users/JackIrvine/opt/anaconda3/envs/jackirvine/lib/python3.8/site-packages/pyproprop/processed_property.py", line 537, in apply_method
    if optional and value is None:
NameError: name 'optional' is not defined
```

**Comment by brocksam** [comment]
Minimal reproducer please, not console readout of the error message.

**Comment by jackirvine97** [comment]
> Minimal reproducer please, not console readout of the error message.

Apologies.

Yes this is 0.4.0.

The following is reproduces it:

```
import numpy as np
from pyproprop import processed_property


class SomeClass:

    squares = processed_property(
        "squares",
        type=int,
        method=np.square,

    )

    def __init__(self, squares):
        self.squares = squares

x = SomeClass(4)
print(x.squares)
```
